const f=(key,label,type='text',value='',choices)=>({key,label,type,default:String(value),choices});
const text=(k,l,v='')=>f(k,l,'text',v),number=(k,l,v=0)=>f(k,l,'number',v),choice=(k,l,values)=>f(k,l,'choice',values[0],values);
const pick=(k,l,lookup,autoId=false)=>({...text(k,l),lookup,autoId});
const target=pick('playerId','대상 플레이어','players'), id=pick('id','기록 ID (신규는 비워 두세요)','projects',true);
const region=choice('region',"구역",['agri','port','industry','global']);
const active=choice('isActive',"사용 여부",['true','false']);
const ops=[];
function op(action,label,section,fields=[],write=false){ops.push({action,label,section,fields:write?[...fields,text('reason',"작업 사유")]:fields,write});}
op('players',"플레이어·잔액 조회",'wallet',[text('search',"검색")]);
for(const [a,l] of [['wallet_add',"돈 지급"],['wallet_subtract',"돈 차감"],['wallet_set',"잔액 직접 설정"]])op(a,l,'wallet',[target,number('amount',"금액",1),...(a==='wallet_set'?[number('expectedBalance',"확인한 현재 잔액")]:[])],true);
op('wallet_all',"등록된 전체 플레이어에게 지급",'wallet',[number('amount',"금액",1)],true);
op('player_freeze',"경제 이용 정지 설정",'wallet',[target,choice('frozen',"이용 정지",['true','false'])],true);
op('shop_list',"상품 조회",'shop',[text('search',"검색")]);
op('shop_save',"상품 등록·수정",'shop',[text('itemId',"아이템 ID"),text('itemName',"아이템 이름"),choice('category',"분류",['agri','port','industry','misc']),number('buyPrice',"구매 가격",1),number('sellPrice',"판매 가격",0),number('stockQuantity',"재고 수량",200),number('replenishAmount',"재입고 수량",50),number('replenishIntervalSeconds',"재입고 주기(초)",300),active],true);
op('shop_disable',"상품 판매 중지",'shop',[text('itemId',"아이템 ID")],true);
op('rules_get',"경제 설정 조회",'rules');
op('rules_save',"경제 설정 변경",'rules',[choice('maintenance',"경제 점검 상태",['false','true']),number('buyFeeRate',"구매 수수료율",.02),number('sellFeeRate',"판매 수수료율",.03),number('minFee',"최소 수수료"),number('maxSellQuantity',"최대 판매 수량",1000),number('flipCooldownSeconds',"반대 거래 대기 시간(초)",10),number('deliveryActiveLimit',"동시 진행 의뢰 수",3),number('projectRewardRate',"프로젝트 보상 비율",.2),number('walletLimit',"지갑 잔액 상한",2147483647)],true);
op('deliveries',"납품 의뢰 정책 조회",'delivery');
op('delivery_save',"납품 의뢰 등록·수정",'delivery',[pick('id','의뢰 정책 ID (신규 자동 생성)','deliveries',true),text('title',"제목"),text('description',"설명"),text('itemId',"아이템 ID"),number('quantity',"수량",1),number('reward',"보상",1),number('cooldownSeconds',"반복 대기 시간(초)",0)],true);
op('delivery_disable',"납품 의뢰 모집 중지",'delivery',[pick('id','의뢰 정책 ID','deliveries')],true);
op('contracts',"수락한 납품 의뢰 조회",'delivery',[target]);
op('delivery_cancel',"의뢰 취소·납품 아이템 반환",'delivery',[pick('id','납품 의뢰','contracts')],true);
op('rewards',"보상 정책 조회",'reward');
op('reward_save',"보상 정책 등록·수정",'reward',[pick('id','보상 ID (신규 자동 생성)','rewards',true),number('amount',"보상",1),number('cooldownSeconds',"반복 대기 시간(초)",0)],true);
op('reward_reset',"보상 수령 제한 초기화",'reward',[target,pick('id','보상 ID','rewards')],true);
op('mail_list',"플레이어 우편 조회",'mail',[target]);
op('mail_send',"돈·아이템 복구 우편 발송",'mail',[target,text('title',"제목",'아이템 복구'),text('message',"내용"),number('rewardAmount',"지급할 돈"),text('itemId',"아이템 ID (선택)"),number('quantity',"아이템 수량",1),choice('copyHeld',"손에 든 아이템 원본 데이터 복사",['false','true'])],true);
op('mail_all',"등록된 전체 플레이어에게 우편 발송",'mail',[text('title',"제목"),text('message',"내용"),number('rewardAmount',"지급할 돈")],true);
op('mail_cancel',"미수령 우편 취소",'mail',[pick('id','우편','mail')],true);
op('projects',"프로젝트",'project');
op('project_save',"프로젝트 등록·수정",'project',[id,text('name',"이름"),text('description',"설명"),number('targetAmount',"목표 금액",1000),region,text('endsAt',"종료 시각 (ISO 형식, 선택)")],true);
op('project_complete',"프로젝트 완료·보상 발급",'project',[pick('id','프로젝트','projects')],true);
op('project_refund',"프로젝트 취소·기여금 환불",'project',[pick('id','프로젝트','projects')],true);
op('project_effect',"프로젝트 효과 변경",'project',[pick('id','프로젝트','projects'),choice('effectType',"효과",['price_bonus','xp_bonus','focus_bonus']),choice('effectTarget',"효과 적용 구역",['agri','port','industry','global']),number('effectValue',"추가 효과 비율 (0.1 = 10%)",0.1),active],true);
op('events','이벤트 조회','event');
op('event_save',"이벤트 등록·수정",'event',[pick('id','기록 ID (신규는 비워 두세요)','events',true),text('name',"이름"),text('description',"설명"),region,choice('effectType',"효과",['price_bonus','xp_bonus']),number('effectValue',"추가 효과 비율 (0.1 = 10%)",0.1),choice('status',"현황",['draft','active','ended']),text('startsAt',"시작 시각 (ISO 형식, 선택)"),text('endsAt',"종료 시각 (ISO 형식, 선택)")],true);
op('event_end',"이벤트 종료",'event',[pick('id','이벤트','events')],true);
op('regions',"구역 진행도 조회",'region');
op('region_set',"구역 경험치 설정",'region',[region,number('progress',"경험치")],true);
op('focus_set',"집중 구역 설정",'region',[choice('region',"집중 구역",['agri','port','industry','none'])],true);
op('logs',"금전·관리자 작업 기록",'logs',[pick('playerId','대상 플레이어 (선택)','players')]);
op('trade_refund',"원본 구매 내역 1회 환불",'recovery',[pick('sourceId','원본 구매 내역','purchases')],true);
op('game_pending',"미완료 거래·등록 아이템 조회",'recovery',[target]);
op('game_retry',"미완료 거래 재처리",'recovery',[target],true);
op('listing_return',"보관 중인 등록 아이템 반환",'recovery',[target,text('itemId',"아이템 ID")],true);
op('permissions',"관리자 권한 조회",'permissions');
op('permission_set',"OP 경제 관리 권한 설정",'permissions',[pick('actorId','관리자 플레이어','players'),text('permissions',"권한 분류 (예: 지갑, 상점 / * 전체)")],true);
op('health',"DB·감사 기록 상태",'logs');
export const ADMIN_CATALOG=ops;
